<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddDataTableCountries extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AF', 'Afghanistan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AL', 'Albania');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('DZ', 'Algeria');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('DS', 'American Samoa');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AD', 'Andorra');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AO', 'Angola');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AI', 'Anguilla');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AQ', 'Antarctica');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AG', 'Antigua and Barbuda');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AR', 'Argentina');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AM', 'Armenia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AW', 'Aruba');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AU', 'Australia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AT', 'Austria');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AZ', 'Azerbaijan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BS', 'Bahamas');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BH', 'Bahrain');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BD', 'Bangladesh');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BB', 'Barbados');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BY', 'Belarus');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BE', 'Belgium');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BZ', 'Belize');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BJ', 'Benin');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BM', 'Bermuda');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BT', 'Bhutan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BO', 'Bolivia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BA', 'Bosnia and Herzegovina');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BW', 'Botswana');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BV', 'Bouvet Island');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BR', 'Brazil');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('IO', 'British Indian Ocean Territory');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BN', 'Brunei Darussalam');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BG', 'Bulgaria');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BF', 'Burkina Faso');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('BI', 'Burundi');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('KH', 'Cambodia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CM', 'Cameroon');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CA', 'Canada');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CV', 'Cape Verde');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('KY', 'Cayman Islands');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CF', 'Central African Republic');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TD', 'Chad');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CL', 'Chile');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CN', 'China');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CX', 'Christmas Island');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CC', 'Cocos (Keeling) Islands');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CO', 'Colombia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('KM', 'Comoros');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CG', 'Congo');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CK', 'Cook Islands');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CR', 'Costa Rica');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('HR', 'Croatia (Hrvatska)');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CU', 'Cuba');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CY', 'Cyprus');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CZ', 'Czech Republic');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('DK', 'Denmark');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('DJ', 'Djibouti');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('DM', 'Dominica');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('DO', 'Dominican Republic');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TP', 'East Timor');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('EC', 'Ecuador');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('EG', 'Egypt');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SV', 'El Salvador');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GQ', 'Equatorial Guinea');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('ER', 'Eritrea');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('EE', 'Estonia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('ET', 'Ethiopia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('FK', 'Falkland Islands (Malvinas)');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('FO', 'Faroe Islands');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('FJ', 'Fiji');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('FI', 'Finland');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('FR', 'France');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('FX', 'France, Metropolitan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GF', 'French Guiana');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('PF', 'French Polynesia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TF', 'French Southern Territories');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GA', 'Gabon');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GM', 'Gambia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GE', 'Georgia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('DE', 'Germany');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GH', 'Ghana');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GI', 'Gibraltar');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GK', 'Guernsey');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GR', 'Greece');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GL', 'Greenland');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GD', 'Grenada');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GP', 'Guadeloupe');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GU', 'Guam');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GT', 'Guatemala');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GN', 'Guinea');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GW', 'Guinea-Bissau');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GY', 'Guyana');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('HT', 'Haiti');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('HM', 'Heard and Mc Donald Islands');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('HN', 'Honduras');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('HK', 'Hong Kong');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('HU', 'Hungary');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('IS', 'Iceland');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('IN', 'India');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('IM', 'Isle of Man');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('ID', 'Indonesia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('IR', 'Iran (Islamic Republic of)');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('IQ', 'Iraq');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('IE', 'Ireland');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('IL', 'Israel');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('IT', 'Italy');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CI', 'Ivory Coast');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('JE', 'Jersey');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('JM', 'Jamaica');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('JP', 'Japan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('JO', 'Jordan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('KZ', 'Kazakhstan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('KE', 'Kenya');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('KI', 'Kiribati');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('KP', 'Korea, Democratic People''s Republic of');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('KR', 'Korea, Republic of');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('XK', 'Kosovo');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('KW', 'Kuwait');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('KG', 'Kyrgyzstan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('LA', 'Lao People''s Democratic Republic');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('LV', 'Latvia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('LB', 'Lebanon');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('LS', 'Lesotho');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('LR', 'Liberia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('LY', 'Libyan Arab Jamahiriya');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('LI', 'Liechtenstein');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('LT', 'Lithuania');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('LU', 'Luxembourg');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MO', 'Macau');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MK', 'Macedonia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MG', 'Madagascar');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MW', 'Malawi');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MY', 'Malaysia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MV', 'Maldives');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('ML', 'Mali');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MT', 'Malta');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MH', 'Marshall Islands');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MQ', 'Martinique');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MR', 'Mauritania');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MU', 'Mauritius');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TY', 'Mayotte');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MX', 'Mexico');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('FM', 'Micronesia, Federated States of');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MD', 'Moldova, Republic of');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MC', 'Monaco');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MN', 'Mongolia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('ME', 'Montenegro');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MS', 'Montserrat');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MA', 'Morocco');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MZ', 'Mozambique');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MM', 'Myanmar');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('NA', 'Namibia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('NR', 'Nauru');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('NP', 'Nepal');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('NL', 'Netherlands');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AN', 'Netherlands Antilles');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('NC', 'New Caledonia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('NZ', 'New Zealand');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('NI', 'Nicaragua');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('NE', 'Niger');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('NG', 'Nigeria');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('NU', 'Niue');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('NF', 'Norfolk Island');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('MP', 'Northern Mariana Islands');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('NO', 'Norway');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('OM', 'Oman');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('PK', 'Pakistan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('PW', 'Palau');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('PS', 'Palestine');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('PA', 'Panama');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('PG', 'Papua New Guinea');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('PY', 'Paraguay');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('PE', 'Peru');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('PH', 'Philippines');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('PN', 'Pitcairn');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('PL', 'Poland');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('PT', 'Portugal');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('PR', 'Puerto Rico');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('QA', 'Qatar');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('RE', 'Reunion');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('RO', 'Romania');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('RU', 'Russian Federation');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('RW', 'Rwanda');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('KN', 'Saint Kitts and Nevis');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('LC', 'Saint Lucia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('VC', 'Saint Vincent and the Grenadines');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('WS', 'Samoa');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SM', 'San Marino');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('ST', 'Sao Tome and Principe');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SA', 'Saudi Arabia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SN', 'Senegal');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('RS', 'Serbia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SC', 'Seychelles');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SL', 'Sierra Leone');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SG', 'Singapore');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SK', 'Slovakia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SI', 'Slovenia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SB', 'Solomon Islands');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SO', 'Somalia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('ZA', 'South Africa');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GS', 'South Georgia South Sandwich Islands');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SS', 'South Sudan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('ES', 'Spain');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('LK', 'Sri Lanka');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SH', 'St. Helena');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('PM', 'St. Pierre and Miquelon');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SD', 'Sudan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SR', 'Suriname');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SJ', 'Svalbard and Jan Mayen Islands');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SZ', 'Swaziland');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SE', 'Sweden');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('CH', 'Switzerland');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('SY', 'Syrian Arab Republic');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TW', 'Taiwan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TJ', 'Tajikistan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TZ', 'Tanzania, United Republic of');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TH', 'Thailand');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TG', 'Togo');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TK', 'Tokelau');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TO', 'Tonga');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TT', 'Trinidad and Tobago');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TN', 'Tunisia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TR', 'Turkey');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TM', 'Turkmenistan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TC', 'Turks and Caicos Islands');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('TV', 'Tuvalu');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('UG', 'Uganda');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('UA', 'Ukraine');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('AE', 'United Arab Emirates');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('GB', 'United Kingdom');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('US', 'United States');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('UM', 'United States minor outlying islands');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('UY', 'Uruguay');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('UZ', 'Uzbekistan');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('VU', 'Vanuatu');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('VA', 'Vatican City State');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('VE', 'Venezuela');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('VN', 'Vietnam');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('VG', 'Virgin Islands (British)');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('VI', 'Virgin Islands (U.S.)');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('WF', 'Wallis and Futuna Islands');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('EH', 'Western Sahara');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('YE', 'Yemen');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('ZR', 'Zaire');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('ZM', 'Zambia');");
        DB::statement("INSERT INTO `countries` (number_order,name) VALUES ('ZW', 'Zimbabwe');");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
